apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-03-24T11:12:25Z"
  labels:
    app: currency-exchange-service-k8s
  name: currency-exchange-service-k8s
  namespace: default
  resourceVersion: "23962"
  uid: 6631afeb-87c3-4df2-8da3-07c31995c9c3
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.99.16.105
  clusterIPs:
  - 10.99.16.105
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31940
    port: 8300
    protocol: TCP
    targetPort: 8300
  selector:
    app: currency-exchange-service-k8s
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: localhost
