version: '3.7'

services:

  currency-exchange:
    image: amreshra/currency-exchange-service:0.1
    mem_limit: 700m
    ports:
      - "8200:8200"
    networks:
      - currency-network
    depends_on:
      - naming-server
#      - rabnitmq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
#      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
#      SPRING_RABBITMQ_HOST: rabbitmq
#      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      
  currency-conversion:
    image:  amreshra/currency-conversion-service:0.1
    mem_limit: 700m
    ports:
      - "8100:8100"
    networks:
      - currency-network
    depends_on:
      - naming-server
#      - rabnitmq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
#      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
#      SPRING_RABBITMQ_HOST: rabbitmq
#      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      
  api-gateway:
    image: amreshra/api-gateway:0.1
    mem_limit: 700m
    ports:
      - "8765:8765"
    networks:
      - currency-network
    depends_on:
      - naming-server
#      - rabnitmq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
#      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
#      SPRING_RABBITMQ_HOST: rabbitmq
#      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      
  naming-server:
    image: amreshra/naming-server:0.1
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network
      
  zipkin-server:
    image: openzipkin/zipkin
    mem_limit: 300m
    ports:
      - "9411:9411"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - rabnitmq
#    environment:
#      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
#    restart: always
      
#  rabnitmq:
#    image: rabbitmq
#    mem_limit: 300m
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    networks:
#      - currency-network
      
networks:
  currency-network: